# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build_python3.6:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-py36-{{ checksum ".circleci/config.yml" }}

      - run:
          name: install conda and dependencies
          command: |
            test -d ~/miniconda3 && exit 0
            echo "Installing a fresh version of Miniconda."
            MINICONDA_URL="https://repo.continuum.io/miniconda"
            MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
            curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
            bash $MINICONDA_FILE -b
            source ~/miniconda3/bin/activate root
            conda create -c conda-forge/label/cf201901 -n pynio gcc setuptools python=3.6 numpy=1.14 g2clib=1.6 hdf4 hdf5 hdfeos2 hdfeos5 jasper libgdal libnetcdf proj4 pytest

      - save_cache:
          paths:
            - ~/miniconda3
          key: v1-dependencies-py36-{{ checksum ".circleci/config.yml" }}

      - run:
          name: build pynio
          command: |
            source ~/miniconda3/bin/activate pynio
            bash build_py3.sh


      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            source ~/miniconda3/bin/activate pynio
            cd test
            py.test

      - store_artifacts:
          path: test-reports
          destination: test-reports
